version: '3.4'

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
  gameteq.testwork.webinputfileservice:
    image: ${DOCKER_REGISTRY-}gameteqtestworkwebinputfileservice
    build:
      context: .
      dockerfile: GameTeq.TestWork.WebInputFileService/Dockerfile

  gameteq.testwork.localfilesservice:
    image: ${DOCKER_REGISTRY-}gameteqtestworklocalfilesservice
    build:
      context: .
      dockerfile: GameTeq.TestWork.LocalFilesService/Dockerfile
